### ISSUE TITLE
Any reason to define alot of user messages as variable?

### ISSUE THREAD

**Issue by hamcos** [cunninghamp/Get-DAGHealth.ps1#2]
Maybe a templating concept would be better suited for the small number of cases where a variable is used more then once.

**Comment by cunninghamp** [comment]
Yes. Simplified editing, as well as some localization issues for non-English systems, and was a test for another larger script. This script isn't being maintained, Test-ExchangeServerHealth.ps1 is where any improvements will be made. A new version of that script is also in development, it will likely break out the strings into a separate config file.
